from django.urls import path

from apps.pc_compat import views
from apps.pc_compat import (
    views_address,
    views_asset,
    views_auth,
    views_catalog,
    views_company,
    views_consult,
    views_district,
    views_download,
    views_evaluate,
    views_invoice,
    views_order,
    views_pay,
    views_profile,
)

urlpatterns = [
    path("register.ajax", views_auth.register, name="pc-register"),
    path("getVerifyCode.ajax", views_auth.get_verify_code, name="pc-getVerifyCode"),
    path(
        "getVerifyCodeFindPw.ajax",
        views_auth.get_verify_code_find_pw,
        name="pc-getVerifyCodeFindPw",
    ),
    path("telCodeVerify.ajax", views_auth.tel_code_verify, name="pc-telCodeVerify"),
    path("downloadFile.ajax", views_download.download_file, name="pc-downloadFile"),
    path("getUserBasicInfo.ajax", views.get_user_basic_info, name="pc-getUserBasicInfo"),
    path("updateUserBasicInfo.ajax", views_profile.update_user_basic_info, name="pc-updateUserBasicInfo"),
    path("setPassword.ajax", views_profile.set_password, name="pc-setPassword"),
    path("updatePhone.ajax", views_profile.update_phone_avatar, name="pc-updatePhone"),
    path("addOrUpdateUserData.ajax", views_profile.add_or_update_user_data, name="pc-addOrUpdateUserData"),
    path("addOrUpdateUserCompanyData.ajax", views_profile.add_or_update_user_company_data, name="pc-addOrUpdateUserCompanyData"),
    path("useraddress.ajax", views_address.user_address, name="pc-useraddress"),
    path("getdeliveryaddress.ajax", views_address.get_delivery_address, name="pc-getdeliveryaddress"),
    path("insertdeliveryaddress.ajax", views_address.insert_delivery_address, name="pc-insertdeliveryaddress"),
    path("updatedeliveryaddress.ajax", views_address.update_delivery_address, name="pc-updatedeliveryaddress"),
    path("deldeliveryaddress.ajax", views_address.del_delivery_address, name="pc-deldeliveryaddress"),
    path("selCompanyName.ajax", views_company.sel_company_name, name="pc-selCompanyName"),
    path("indexClassList.ajax", views_catalog.index_class_list, name="pc-indexClassList"),
    path("bannerList.ajax", views_catalog.banner_list, name="pc-bannerList"),
    path("getXcxBanner.ajax", views_catalog.get_xcx_banner, name="pc-getXcxBanner"),
    path("getTuZheBanner.ajax", views_catalog.get_tuzhe_banner, name="pc-getTuZheBanner"),
    path("selThirdClassList.ajax", views_catalog.sel_third_class_list, name="pc-selThirdClassList"),
    path("selFirAndSecClassList.ajax", views_catalog.sel_fir_and_sec_class_list, name="pc-selFirAndSecClassList"),
    path(
        "selThirdClassByKeyWordList.ajax",
        views_catalog.sel_third_class_by_keyword_list,
        name="pc-selThirdClassByKeyWordList",
    ),
    path("getIntegral.ajax", views_asset.get_integral, name="pc-getIntegral"),
    path("getIntegralConvertRatio.ajax", views_asset.get_integral_convert_ratio, name="pc-getIntegralConvertRatio"),
    path("center/getAccount.ajax", views_asset.get_account, name="pc-getAccount"),
    path("center/getOrderData.ajax", views_order.center_get_order_data, name="pc-getOrderData"),
    path("myExperimentOrderList.ajax", views_order.my_experiment_order_list, name="pc-myExperimentOrderList"),
    path("experimentOrderList.ajax", views_order.experiment_order_list, name="pc-experimentOrderList"),
    path("selTestOrSure.ajax", views_order.sel_test_or_sure, name="pc-selTestOrSure"),
    path("indexExpList.ajax", views_catalog.index_exp_list, name="pc-indexExpList"),
    path("selExpList.ajax", views_catalog.sel_exp_list, name="pc-selExpList"),
    path("testClassDetail.ajax", views_catalog.test_class_detail, name="pc-testClassDetail"),
    path("xcxtestClassDetail.ajax", views_catalog.xcx_test_class_detail, name="pc-xcxtestClassDetail"),
    path("queryProCityCo.ajax", views_district.query_pro_city_co, name="pc-queryProCityCo"),
    path("queryProCityCo1.ajax", views_district.query_pro_city_co1, name="pc-queryProCityCo1"),
    path("writeevaluate.ajax", views_evaluate.write_evaluate, name="pc-writeevaluate"),
    path("serviceConsultAdd.ajax", views_consult.service_consult_add, name="pc-serviceConsultAdd"),
    path("expMakeList.ajax", views_consult.exp_make_list, name="pc-expMakeList"),
    path("myExpMakeList.ajax", views_consult.my_exp_make_list, name="pc-myExpMakeList"),
    path("myExpMakeStatusList.ajax", views_consult.my_exp_make_status_list, name="pc-myExpMakeStatusList"),
    path("saveServiceConsult.ajax", views_consult.save_service_consult, name="pc-saveServiceConsult"),
    path("cancelConsult.ajax", views_consult.cancel_consult, name="pc-cancelConsult"),
    path("printYyd.ajax", views_consult.print_yyd, name="pc-printYyd"),
    path("center/getIntegralList.ajax", views_asset.get_integral_list, name="pc-getIntegralList"),
    path("center/getInvoiceList.ajax", views_invoice.get_invoice_list, name="pc-getInvoiceList"),
    path(
        "center/getInvoiceOrderList.ajax",
        views_invoice.get_invoice_order_list,
        name="pc-getInvoiceOrderList",
    ),
    path("center/applyInvoice.ajax", views_invoice.apply_invoice, name="pc-applyInvoice"),
    path(
        "center/getInvoiceLogList.ajax",
        views_invoice.get_invoice_log_list,
        name="pc-getInvoiceLogList",
    ),
    path("center/getInvoiceInfo.ajax", views_invoice.get_invoice_info, name="pc-getInvoiceInfo"),
    path("getinvoiceInfo.ajax", views_invoice.get_invoice_info_list, name="pc-getinvoiceInfo"),
    path("insertinvoiceInfo.ajax", views_invoice.insert_invoice_info, name="pc-insertinvoiceInfo"),
    path("updateinvoiceInfo.ajax", views_invoice.update_invoice_info, name="pc-updateinvoiceInfo"),
    path("delinvoiceInfo.ajax", views_invoice.del_invoice_info, name="pc-delinvoiceInfo"),
    path("addInvoiceInfo.ajax", views_invoice.add_invoice_info_legacy, name="pc-addInvoiceInfo"),
    path("cancelInvoiceInfo.ajax", views_invoice.cancel_invoice_info, name="pc-cancelInvoiceInfo"),
    path("amountPay.ajax", views_pay.amount_pay, name="pc-amountPay"),
    path("prePay.ajax", views_pay.pre_pay, name="pc-prePay"),
    path("preAmountPay.ajax", views_pay.pre_amount_pay, name="pc-preAmountPay"),
    path("rechargePrePay.ajax", views_pay.recharge_pre_pay, name="pc-rechargePrePay"),
    path("rechargeContinuePay.ajax", views_pay.recharge_continue_pay, name="pc-rechargeContinuePay"),
    path("addRecharge.ajax", views_pay.add_recharge_view, name="pc-addRecharge"),
    path(
        "selRechargeStatus.ajax",
        views_pay.sel_recharge_status_view,
        name="pc-selRechargeStatus",
    ),
    path(
        "selRechargeList.ajax",
        views_pay.sel_recharge_list_view,
        name="pc-selRechargeList",
    ),
    path(
        "selDefaultAccount.ajax",
        views_pay.sel_default_account_view,
        name="pc-selDefaultAccount",
    ),
    path("addCash.ajax", views_pay.add_cash_view, name="pc-addCash"),
    path("saveaccessory.ajax", views_pay.save_accessory_view, name="pc-saveaccessory"),
    path("queryPayStatus.ajax", views_pay.query_pay_status, name="pc-queryPayStatus"),
    path("queryPayStatusByOrder.ajax", views_pay.query_pay_status_by_order, name="pc-queryPayStatusByOrder"),
    path("pay.ajax", views_pay.wechat_pay_notify, name="pc-payNotify"),
    path("rechargePay.ajax", views_pay.wechat_recharge_notify, name="pc-rechargePayNotify"),
    path("amountPayBack.ajax", views_pay.wechat_amount_pay_back, name="pc-amountPayBack"),
]
