import { createRouter, createWebHashHistory, type RouteRecordRaw } from 'vue-router'
import Layout from '@/layout/index.vue'

export const constantRoutes: RouteRecordRaw[] = [
  {
    path: '/login',
    name: 'Login',
    component: () => import('@/views/login/index.vue'),
    meta: { title: '登录', hidden: true, noTagsView: true },
  },
  {
    path: '/redirect',
    component: Layout,
    meta: { hidden: true },
    children: [
      {
        path: '/redirect/:path(.*)',
        component: () => import('@/views/redirect/index.vue'),
      },
    ],
  },
  {
    path: '/',
    component: Layout,
    redirect: '/dashboard',
    children: [
      {
        path: 'dashboard',
        name: 'Dashboard',
        component: () => import('@/views/dashboard/index.vue'),
        meta: { title: '欢迎页', affix: true },
      },
      {
        path: 'invoice/apply',
        name: 'InvoiceApply',
        component: () => import('@/views/invoice/apply/index.vue'),
        meta: { title: '发票申请管理' },
      },
      {
        path: 'payment/records',
        name: 'PaymentRecords',
        component: () => import('@/views/payment/records/index.vue'),
        meta: { title: '支付记录管理' },
      },
      {
        path: 'payment/application',
        name: 'PaymentApplication',
        component: () => import('@/views/payment/application/index.vue'),
        meta: { title: '用户还款/付款申请管理' },
      },
      {
        path: 'orders/retest',
        name: 'RetestApplication',
        component: () => import('@/views/orders/retest/index.vue'),
        meta: { title: '用户复测管理' },
      },
      {
        path: 'order-settings/tax-rate',
        name: 'TaxRateSetting',
        component: () => import('@/views/order-settings/tax-rate/index.vue'),
        meta: { title: '税率管理' },
      },
      {
        path: 'order-settings/payment-method',
        name: 'PaymentMethodSetting',
        component: () => import('@/views/order-settings/payment-method/index.vue'),
        meta: { title: '收付款方式' },
      },
      {
        path: 'order-settings/auto-evaluate',
        name: 'AutoEvaluateSetting',
        component: () => import('@/views/order-settings/auto-evaluate/index.vue'),
        meta: { title: '自动评价设置' },
      },
      {
        path: 'order-settings/outgoing-invoice',
        name: 'OutgoingInvoiceSetting',
        component: () => import('@/views/order-settings/outgoing-invoice/index.vue'),
        meta: { title: '出项发票管理' },
      },
      {
        path: 'order-settings/incoming-invoice',
        name: 'IncomingInvoiceSetting',
        component: () => import('@/views/order-settings/incoming-invoice/index.vue'),
        meta: { title: '进项发票管理' },
      },
      {
        path: 'order-settings/order-type',
        name: 'OrderTypeSetting',
        component: () => import('@/views/order-settings/order-type/index.vue'),
        meta: { title: '订单类型管理' },
      },
      {
        path: 'system/depts',
        name: 'SystemDepts',
        component: () => import('@/views/system/depts/index.vue'),
        meta: { title: '部门管理' },
      },
      {
        path: 'system/ops-logs',
        name: 'SystemOpsLogs',
        component: () => import('@/views/system/ops-logs/index.vue'),
        meta: { title: '系统操作日志' },
      },
      {
        path: 'system/users',
        name: 'SystemUsers',
        component: () => import('@/views/system/users/index.vue'),
        meta: { title: '用户管理' },
      },
      {
        path: 'system/roles',
        name: 'SystemRoles',
        component: () => import('@/views/system/roles/index.vue'),
        meta: { title: '角色管理' },
      },
      {
        path: 'system/menus',
        name: 'SystemMenus',
        component: () => import('@/views/system/menus/index.vue'),
        meta: { title: '菜单管理' },
      },
      {
        path: 'system/districts',
        name: 'SystemDistricts',
        component: () => import('@/views/system/districts/index.vue'),
        meta: { title: '行政区划管理' },
      },
      {
        path: 'system/user-types',
        name: 'SystemUserTypes',
        component: () => import('@/views/system/user-types/index.vue'),
        meta: { title: '用户类型管理' },
      },
      {
        path: 'system/areas',
        name: 'SystemAreas',
        component: () => import('@/views/system/areas/index.vue'),
        meta: { title: '区域管理' },
      },
      {
        path: 'system/companies',
        name: 'SystemCompanies',
        component: () => import('@/views/system/companies/index.vue'),
        meta: { title: '所属公司管理' },
      },
      {
        path: 'system/app-users',
        name: 'SystemAppUsers',
        component: () => import('@/views/system/app-users/index.vue'),
        meta: { title: 'App用户管理' },
      },
      {
        path: 'system/test-addresses',
        name: 'SystemTestAddresses',
        component: () => import('@/views/system/test-addresses/index.vue'),
        meta: { title: '测试地址管理' },
      },
      {
        path: 'system/company-accounts',
        name: 'SystemCompanyAccounts',
        component: () => import('@/views/system/company-accounts/index.vue'),
        meta: { title: '公司账户管理' },
      },
      {
        path: 'service-platform/service-apply',
        name: 'ServiceApply',
        component: () => import('@/views/service-platform/service-apply/index.vue'),
        meta: { title: '服务申请' },
      },
      {
        path: 'service-platform/buyback',
        name: 'ServiceBuyback',
        component: () => import('@/views/service-platform/buyback/index.vue'),
        meta: { title: '设备回购管理' },
      },
      {
        path: 'service-platform/consult',
        name: 'ServiceConsult',
        component: () => import('@/views/service-platform/consult/index.vue'),
        meta: { title: '咨询管理' },
      },
      {
        path: 'service-platform/consult-message',
        name: 'ServiceConsultMessage',
        component: () => import('@/views/service-platform/consult-message/index.vue'),
        meta: { title: '咨询消息设置' },
      },
      {
        path: 'service-platform/faq',
        name: 'ServiceFaq',
        component: () => import('@/views/service-platform/faq/index.vue'),
        meta: { title: '常见问题管理' },
      },
      {
        path: 'service-platform/evaluated-sub-orders',
        name: 'ServiceEvaluatedSubOrders',
        component: () => import('@/views/service-platform/evaluated-sub-orders/index.vue'),
        meta: { title: '已评价分包订单' },
      },
      {
        path: 'service-platform/evaluated-orders',
        name: 'ServiceEvaluatedOrders',
        component: () => import('@/views/service-platform/evaluated-orders/index.vue'),
        meta: { title: '已评价实验订单' },
      },
      {
        path: 'service-platform/records',
        name: 'ServiceRecords',
        component: () => import('@/views/service-platform/records/index.vue'),
        meta: { title: '沟通记录管理' },
      },
      {
        path: 'service-platform/proposals',
        name: 'ServiceProposals',
        component: () => import('@/views/service-platform/proposals/index.vue'),
        meta: { title: '建议反馈管理' },
      },
      {
        path: 'service-platform/customer-service',
        name: 'ServiceCustomerService',
        component: () => import('@/views/service-platform/customer-service/index.vue'),
        meta: { title: '客服显示设置' },
      },
      {
        path: 'service-platform/openid',
        name: 'ServiceOpenid',
        component: () => import('@/views/service-platform/openid/index.vue'),
        meta: { title: 'OpenID管理' },
      },
      // 运营管理
      {
        path: 'ops/advert',
        name: 'OpsAdvert',
        component: () => import('@/views/ops/advert/index.vue'),
        meta: { title: '广告管理' },
      },
      {
        path: 'ops/adv-pos',
        name: 'OpsAdvPos',
        component: () => import('@/views/ops/adv-pos/index.vue'),
        meta: { title: '广告位管理' },
      },
      {
        path: 'ops/banner-pc',
        name: 'OpsBannerPc',
        component: () => import('@/views/ops/banner/index.vue'),
        meta: { title: '轮播图管理', bannerType: 0 },
      },
      {
        path: 'ops/banner-xcx',
        name: 'OpsBannerXcx',
        component: () => import('@/views/ops/banner/index.vue'),
        meta: { title: '小程序轮播图管理', bannerType: 1 },
      },
      {
        path: 'ops/banner-xcxfm',
        name: 'OpsBannerXcxfm',
        component: () => import('@/views/ops/banner/index.vue'),
        meta: { title: '小程序加载页面配置', bannerType: 2 },
      },
      {
        path: 'ops/setting-device',
        name: 'OpsSettingDevice',
        component: () => import('@/views/ops/setting/index.vue'),
        meta: { title: '设备服务设置', settingType: 'deviceservice' },
      },
      {
        path: 'ops/setting-product',
        name: 'OpsSettingProduct',
        component: () => import('@/views/ops/setting/index.vue'),
        meta: { title: '产品测试设置', settingType: 'product' },
      },
      {
        path: 'ops/setting-business',
        name: 'OpsSettingBusiness',
        component: () => import('@/views/ops/setting/index.vue'),
        meta: { title: '商业支持设置', settingType: 'business' },
      },
      {
        path: 'ops/setting-secondhand',
        name: 'OpsSettingSecondhand',
        component: () => import('@/views/ops/setting/index.vue'),
        meta: { title: '二手仪器设置', settingType: 'secondhand' },
      },
      {
        path: 'ops/setting-rent',
        name: 'OpsSettingRent',
        component: () => import('@/views/ops/setting/index.vue'),
        meta: { title: '租赁仪器设置', settingType: 'rent' },
      },
      {
        path: 'ops/redeem',
        name: 'OpsRedeem',
        component: () => import('@/views/ops/redeem/index.vue'),
        meta: { title: '用户兑换记录' },
      },
      {
        path: 'ops/comment',
        name: 'OpsComment',
        component: () => import('@/views/ops/comment/index.vue'),
        meta: { title: '评论审核管理' },
      },
      {
        path: 'ops/whitelist',
        name: 'OpsWhitelist',
        component: () => import('@/views/ops/whitelist/index.vue'),
        meta: { title: '白名单配置管理' },
      },
      {
        path: 'ops/entry',
        name: 'OpsEntry',
        component: () => import('@/views/ops/entry/index.vue'),
        meta: { title: '帖子列表管理' },
      },
      {
        path: 'ops/goods',
        name: 'OpsGoods',
        component: () => import('@/views/ops/goods/index.vue'),
        meta: { title: '产品管理' },
      },
      {
        path: 'ops/spec',
        name: 'OpsSpec',
        component: () => import('@/views/ops/spec/index.vue'),
        meta: { title: '规格管理' },
      },
      {
        path: 'ops/brand',
        name: 'OpsBrand',
        component: () => import('@/views/ops/brand/index.vue'),
        meta: { title: '品牌管理' },
      },
      {
        path: 'ops/goods-type',
        name: 'OpsGoodsType',
        component: () => import('@/views/ops/goods-type/index.vue'),
        meta: { title: '类型管理' },
      },
      {
        path: 'ops/goods-class',
        name: 'OpsGoodsClass',
        component: () => import('@/views/ops/goods-class/index.vue'),
        meta: { title: '分类管理' },
      },
      {
        path: 'ops/album',
        name: 'OpsAlbum',
        component: () => import('@/views/ops/album/index.vue'),
        meta: { title: '相册管理' },
      },
      {
        path: 'ops/goods-evaluate',
        name: 'OpsGoodsEvaluate',
        component: () => import('@/views/ops/goods-evaluate/index.vue'),
        meta: { title: '评价管理' },
      },
      {
        path: 'ops/consult-config',
        name: 'OpsConsultConfig',
        component: () => import('@/views/ops/consult-config/index.vue'),
        meta: { title: '咨询方式设置' },
      },
      // 数字化中心
      {
        path: 'digital/stats',
        name: 'DigitalStats',
        component: () => import('@/views/digital/stats/index.vue'),
        meta: { title: '统计' },
      },
      {
        path: 'digital/test-plan',
        name: 'DigitalTestPlan',
        component: () => import('@/views/digital/plan/index.vue'),
        meta: { title: '实验室人员产出计划设定', planMode: 'test' },
      },
      {
        path: 'digital/lab-test-perf',
        name: 'DigitalLabTestPerf',
        component: () => import('@/views/digital/lab-test-perf/index.vue'),
        meta: { title: '实验室测试人员绩效' },
      },
      {
        path: 'digital/sale-plan',
        name: 'DigitalSalePlan',
        component: () => import('@/views/digital/plan/index.vue'),
        meta: { title: '销售人员产出计划设定', planMode: 'sale' },
      },
      {
        path: 'digital/lab-sale-perf',
        name: 'DigitalLabSalePerf',
        component: () => import('@/views/digital/lab-sale-perf/index.vue'),
        meta: { title: '实验室销售人员绩效' },
      },
      {
        path: 'digital/lab-sale-perf/orders',
        name: 'DigitalLabSalePerfOrders',
        component: () => import('@/views/digital/lab-sale-perf/orders.vue'),
        meta: { title: '销售实际业绩订单明细', hidden: true },
      },
      // 库存管理
      {
        path: 'inventory/list',
        name: 'InventoryList',
        component: () => import('@/views/inventory/list/index.vue'),
        meta: { title: '库存管理' },
      },
      {
        path: 'inventory/warehouses',
        name: 'InventoryWarehouses',
        component: () => import('@/views/inventory/warehouses/index.vue'),
        meta: { title: '仓库管理' },
      },
      {
        path: 'inventory/warehouse-config',
        name: 'InventoryWarehouseConfig',
        component: () => import('@/views/inventory/warehouse-config/index.vue'),
        meta: { title: '仓库配置' },
      },
      {
        path: 'inventory/income',
        name: 'InventoryIncome',
        component: () => import('@/views/inventory/income/index.vue'),
        meta: { title: '内部收益明细' },
      },
      {
        path: 'inventory/labs',
        name: 'InventoryLabs',
        component: () => import('@/views/inventory/labs/index.vue'),
        meta: { title: '实验室管理' },
      },
      {
        path: 'inventory/device-booking',
        name: 'InventoryDeviceBooking',
        component: () => import('@/views/inventory/device-booking/index.vue'),
        meta: { title: '设备预约' },
      },
      {
        path: 'inventory/sample-orders',
        name: 'InventorySampleOrders',
        component: () => import('@/views/inventory/sample-orders/index.vue'),
        meta: { title: '样品管理单' },
      },
      {
        path: 'inventory/sample-warehouses',
        name: 'InventorySampleWarehouses',
        component: () => import('@/views/inventory/sample-warehouses/index.vue'),
        meta: { title: '样品仓库管理' },
      },
      {
        path: 'inventory/sample-retain-warehouses',
        name: 'InventorySampleRetainWarehouses',
        component: () => import('@/views/inventory/sample-retain-warehouses/index.vue'),
        meta: { title: '样品留存仓库管理' },
      },
      // 实验管理
      {
        path: 'experiment/classes',
        name: 'ExperimentClasses',
        component: () => import('@/views/experiment/classes/index.vue'),
        meta: { title: '实验业务类目' },
      },
      {
        path: 'experiment/projects',
        name: 'ExperimentProjects',
        component: () => import('@/views/experiment/projects/index.vue'),
        meta: { title: '实验测试项目' },
      },
      {
        path: 'experiment/goods',
        name: 'ExperimentGoods',
        component: () => import('@/views/experiment/goods/index.vue'),
        meta: { title: '实验产品名称' },
      },
      {
        path: 'experiment/brands',
        name: 'ExperimentBrands',
        component: () => import('@/views/experiment/brands/index.vue'),
        meta: { title: '实验产品品牌' },
      },
      {
        path: 'experiment/sample-attrs',
        name: 'ExperimentSampleAttrs',
        component: () => import('@/views/experiment/sample-attrs/index.vue'),
        meta: { title: '样品属性' },
      },
      {
        path: 'experiment/grab-orders',
        name: 'ExperimentGrabOrders',
        component: () => import('@/views/experiment/grab-orders/index.vue'),
        meta: { title: '抢单实验列表' },
      },
      {
        path: 'experiment/orders',
        name: 'ExperimentOrders',
        component: () => import('@/views/experiment/orders/index.vue'),
        meta: { title: '实验订单' },
      },
      {
        path: 'experiment/sub-orders',
        name: 'ExperimentSubOrders',
        component: () => import('@/views/experiment/sub-orders/index.vue'),
        meta: { title: '实验子订单' },
      },
      {
        path: 'experiment/subcontract-orders',
        name: 'ExperimentSubcontractOrders',
        component: () => import('@/views/experiment/subcontract-orders/index.vue'),
        meta: { title: '实验分包订单' },
      },
      {
        path: 'experiment/subcontract-sub-orders',
        name: 'ExperimentSubcontractSubOrders',
        component: () => import('@/views/experiment/subcontract-sub-orders/index.vue'),
        meta: { title: '实验分包子订单' },
      },
      {
        path: 'experiment/order-detail/:id',
        name: 'ExperimentOrderDetail',
        component: () => import('@/views/experiment/order-detail/index.vue'),
        // hidden：不进侧栏；仍进顶部标签（见 tags-view）
        meta: { title: '订单详情', hidden: true },
      },
      {
        path: 'experiment/order-edit/:id',
        name: 'ExperimentOrderEdit',
        component: () => import('@/views/experiment/order-edit/index.vue'),
        meta: { title: '编辑订单', hidden: true },
      },
      {
        path: 'experiment/sub-order-create',
        name: 'ExperimentSubOrderCreate',
        component: () => import('@/views/experiment/sub-order-create/index.vue'),
        meta: { title: '创建实验子订单', hidden: true },
      },
      // 资金管理
      {
        path: 'fund/account',
        name: 'FundAccount',
        component: () => import('@/views/fund/account/index.vue'),
        meta: { title: '资金账户' },
      },
      {
        path: 'fund/management',
        name: 'FundManagement',
        component: () => import('@/views/fund/management/index.vue'),
        meta: { title: '资金管理' },
      },
      {
        path: 'fund/settings',
        name: 'FundSettings',
        component: () => import('@/views/fund/settings/index.vue'),
        meta: { title: '资金账户设置' },
      },
      {
        path: 'fund/exchange-rate',
        name: 'FundExchangeRate',
        component: () => import('@/views/fund/exchange-rate/index.vue'),
        meta: { title: '美金汇率设置' },
      },
      {
        path: 'fund/account-list',
        name: 'FundAccountList',
        component: () => import('@/views/fund/account-list/index.vue'),
        meta: { title: '资金账户一览' },
      },
      {
        path: 'fund/digital-center',
        name: 'FundDigitalCenter',
        component: () => import('@/views/fund/digital-center/index.vue'),
        meta: { title: '数字化管理运营中心' },
      },
      {
        path: 'fund/company-pay',
        name: 'FundCompanyPay',
        component: () => import('@/views/fund/company-pay/index.vue'),
        meta: { title: '各公司资金支出明细' },
      },
      {
        path: 'fund/personal-pay',
        name: 'FundPersonalPay',
        component: () => import('@/views/fund/personal-pay/index.vue'),
        meta: { title: '个人资金支出明细' },
      },
      {
        path: 'fund/company-loan',
        name: 'FundCompanyLoan',
        component: () => import('@/views/fund/company-loan/index.vue'),
        meta: { title: '各公司借贷款还款' },
      },
      {
        path: 'fund/project-pay',
        name: 'FundProjectPay',
        component: () => import('@/views/fund/project-pay/index.vue'),
        meta: { title: '各项目资金支出明细' },
      },
      // 会员管理
      {
        path: 'member/enterprise',
        name: 'MemberEnterprise',
        component: () => import('@/views/member/enterprise/index.vue'),
        meta: { title: '企业会员管理' },
      },
      {
        path: 'member/personal',
        name: 'MemberPersonal',
        component: () => import('@/views/member/personal/index.vue'),
        meta: { title: '个人会员管理' },
      },
      {
        path: 'member/apply',
        name: 'MemberApply',
        component: () => import('@/views/member/apply/index.vue'),
        meta: { title: '会员申请管理' },
      },
      {
        path: 'member/integral',
        name: 'MemberIntegral',
        component: () => import('@/views/member/integral/index.vue'),
        meta: { title: '会员积分设置' },
      },
      {
        path: 'member/offline-recharge',
        name: 'MemberOfflineRecharge',
        component: () => import('@/views/member/offline-recharge/index.vue'),
        meta: { title: '会员线下充值' },
      },
      {
        path: 'legacy/pending/:menuId',
        name: 'LegacyPending',
        component: () => import('@/views/legacy/pending.vue'),
        meta: { title: '功能迁移中' },
      },
    ],
  },
  {
    path: '/:pathMatch(.*)*',
    name: 'NotFound',
    component: () => import('@/views/error/404.vue'),
    meta: { hidden: true, title: '404', noTagsView: true },
  },
]

const router = createRouter({
  history: createWebHashHistory(),
  scrollBehavior: () => ({ top: 0 }),
  routes: constantRoutes,
})

export default router
